 version: 2.1

 orbs:
   node: circleci/node@3.0.1

 jobs:
   build:
     machine:
       image: ubuntu-1604:201903-01
    
     steps:
       - checkout
       - run: sudo apt-get update
       - run: sudo apt-get install nodejs
       - run: shopt -s dotglob
       - run: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
       - run: add-apt-repository -y 'deb https://download.mono-project.com/repo/ubuntu stable-bionic main'
       - run: node .circleci/index.js

 workflows:
   version: 2
   build:
     jobs:
       - build
