 version: 2.1

 orbs:
   node: circleci/node@3.0.1

 jobs:
   build:
     machine:
       image: ubuntu-1604:201903-01
    
     steps:
       - checkout
       - run: sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
       - run: echo "deb https://download.mono-project.com/repo/ubuntu stable-bionic main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
       - run: sudo apt-get update
       - run: sudo apt-get install -f
       - run: sudo apt-get install mono-complete
       - run: sudo apt-get install nodejs
       - run: node .circleci/index.js

 workflows:
   version: 2
   build:
     jobs:
       - build
