 version: 2.1

 orbs:
   node: circleci/node@3.0.1

 jobs:
   build:
     machine:
       image: ubuntu-1604:201903-01
    
     steps:
       - checkout
       - run: sudo add-apt-repository -y 'deb https://download.mono-project.com/repo/ubuntu stable-bionic main'
       - run: sudo apt-get update
       - run: sudo apt-get install mono-complete
       - run: sudo apt-get install nodejs
       - run: node .circleci/index.js

 workflows:
   version: 2
   build:
     jobs:
       - build
